---
- name: Install system deps
  apt: name={{ item }} state=present
  with_items:
    - acl
    - curl
    - git
    - libexpat1
    - unzip
    - zip

- name: Install Python
  apt: name={{ item }} state=present
  with_items:
     - python2.7
     - libpython2.7
     - libfreetype6
     - libgfortran3
     - libgomp1
